export interface Product {
  id: string;
  name: string;
  slug: string;
  category: string;
  categorySlug: "modern" | "luxury" | "corner";
  image: string; // Main/thumbnail image
  images: string[]; // All product images for gallery
  description: string; // Short description for listings
  fullDescription: string; // Complete detailed description
  keyFeatures: string[]; // Array of feature bullet points
  additionalInfo?: string; // Optional additional information
  href: string;
}

// Category mapping
export const categoryMap = {
  modern: "Moderne Gruppen",
  luxury: "Luxus-Gruppen",
  corner: "Eckgruppen",
} as const;

// All products with multiple images
export const allProducts: Product[] = [
  {
    id: "1",
    name: "Almira Sofa Set",
    slug: "almira",
    category: "Luxus-Gruppen",
    categorySlug: "luxury",
    image: "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.14-2_17_11zon-430x323.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.14-2_17_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.13-2_13_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.13-3_14_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.12-3_9_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.14_19_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.14-1_16_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.12_11_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.15_21_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.12-4_10_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.15-1_20_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.13-1_12_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.12-2_8_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.13_15_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.16-1_22_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/WhatsApp-Image-2021-11-04-at-15.25.16_23_11zon.webp",
    ],
    description: "Das Almira Sofa Set vereint Eleganz und Komfort in einem zeitlosen Design. Mit hochwertigen Materialien und sorgfältiger Handwerkskunst gefertigt, bietet es eine luxuriöse Sitzgelegenheit für Ihr Zuhause.",
    fullDescription: "Das Almira Sofa Set vereint Eleganz und Komfort in einem zeitlosen Design. Mit hochwertigen Materialien und sorgfältiger Handwerkskunst gefertigt, bietet es eine luxuriöse Sitzgelegenheit für Ihr Zuhause. Das opulente Design mit seinen weichen Polstern und eleganten Linien schafft eine warme und einladende Atmosphäre. Perfekt für anspruchsvolle Wohnräume, die Wert auf Qualität und Stil legen.",
    keyFeatures: [
      "Hochwertige Materialien und sorgfältige Handwerkskunst",
      "Opulentes Design mit weichen Polstern",
      "Zeitlose Eleganz für anspruchsvolle Wohnräume",
      "Luxuriöse Sitzgelegenheit mit optimalem Komfort",
    ],
    additionalInfo: "Das Almira Sofa Set ist in verschiedenen Größen und Stoffen erhältlich. Kontaktieren Sie uns für individuelle Beratung und Preise.",
    href: "/kollektionen/almira",
  },
  {
    id: "2",
    name: "Almira Ecksofa",
    slug: "almira-corner",
    category: "Eckgruppen",
    categorySlug: "corner",
    image: "https://cassalini.com/wp-content/uploads/2025/07/casallini_143321_15_11zon-430x323.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143321_15_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143319_13_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143308_4_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143309_5_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143315_10_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143311_7_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143310_6_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143312_8_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143313_9_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143316_11_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143317_12_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143320_14_11zon.webp",
    ],
    description: "Das Almira Ecksofa bietet maximale Flexibilität und Komfort. Die L-Form ermöglicht optimale Raumnutzung und schafft eine gemütliche Atmosphäre für entspannte Stunden mit Familie und Freunden.",
    fullDescription: "Das Almira Ecksofa bietet maximale Flexibilität und Komfort. Die L-Form ermöglicht optimale Raumnutzung und schafft eine gemütliche Atmosphäre für entspannte Stunden mit Familie und Freunden. Mit seinem großzügigen Sitzbereich und weichen Polstern bietet es ausreichend Platz für mehrere Personen. Das elegante Design passt perfekt zu modernen und klassischen Einrichtungsstilen.",
    keyFeatures: [
      "L-Form für optimale Raumnutzung",
      "Großzügiger Sitzbereich für mehrere Personen",
      "Weiche Polsterung für maximalen Komfort",
      "Flexibles Design für verschiedene Raumgrößen",
    ],
    additionalInfo: "Das Almira Ecksofa kann in verschiedenen Konfigurationen und Stoffen bestellt werden. Bitte kontaktieren Sie uns für weitere Details.",
    href: "/kollektionen/almira-corner",
  },
  {
    id: "3",
    name: "Angel Sofa Set",
    slug: "angel",
    category: "Moderne Gruppen",
    categorySlug: "modern",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137372_15-430x323.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137372_15.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137367_11.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137371_14.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137364_10.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137369_12.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137374_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137370_13.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137376_4.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/Angel_01_8_11zon.webp",
    ],
    description: "Das Angel Sofa Set besticht durch seine modernen Linien und minimalistischen Formen. Perfekt für zeitgenössische Wohnräume, die Eleganz und Funktionalität schätzen.",
    fullDescription: "Das Angel Sofa Set besticht durch seine modernen Linien und minimalistischen Formen. Perfekt für zeitgenössische Wohnräume, die Eleganz und Funktionalität schätzen. Mit seinem schlanken Design und hochwertigen Materialien bietet es sowohl Komfort als auch Stil. Die klaren Linien und die zurückhaltende Eleganz machen es zu einem vielseitigen Möbelstück, das sich nahtlos in verschiedene Einrichtungsstile einfügt.",
    keyFeatures: [
      "Moderne Linien und minimalistisches Design",
      "Hochwertige Materialien für Langlebigkeit",
      "Vielseitig für verschiedene Einrichtungsstile",
      "Optimaler Komfort bei schlankem Erscheinungsbild",
    ],
    additionalInfo: "Das Angel Sofa Set ist in verschiedenen Farben erhältlich. Kontaktieren Sie uns für weitere Informationen.",
    href: "/kollektionen/angel",
  },
  {
    id: "4",
    name: "Avanos Sofa Set",
    slug: "avanos",
    category: "Luxus-Gruppen",
    categorySlug: "luxury",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143818-Large_13-430x323.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143818-Large_13.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143804-Large_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143806-Large_3.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143809-Large_5.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143815-Large_10.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143816-Large_11.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143810-Large_6.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143811-Large_7.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143812-Large_8.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143813-Large_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143819-Large_14.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143821-Large_15.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_143822-Large_1.webp",
    ],
    description: "Das Avanos Sofa Set verkörpert luxuriösen Komfort mit seinem opulenten Design und hochwertigen Materialien. Ein Statement-Piece für anspruchsvolle Wohnräume.",
    fullDescription: "Das Avanos Sofa Set verkörpert luxuriösen Komfort mit seinem opulenten Design und hochwertigen Materialien. Ein Statement-Piece für anspruchsvolle Wohnräume. Mit seinen tiefen Polstern und eleganten Details schafft es eine Atmosphäre von unvergleichlichem Komfort und Stil. Das opulente Design mit seinen weichen Formen und hochwertigen Stoffen macht es zum Mittelpunkt jedes Wohnzimmers.",
    keyFeatures: [
      "Opulentes Design mit luxuriösen Materialien",
      "Tiefe Polsterung für maximalen Komfort",
      "Statement-Piece für anspruchsvolle Wohnräume",
      "Hochwertige Verarbeitung und Langlebigkeit",
    ],
    additionalInfo: "Das Avanos Sofa Set ist in verschiedenen Größen und exklusiven Stoffen erhältlich. Für individuelle Beratung kontaktieren Sie uns bitte.",
    href: "/kollektionen/avanos",
  },
  {
    id: "5",
    name: "Belinda Sofa Set",
    slug: "belinda",
    category: "Luxus-Gruppen",
    categorySlug: "luxury",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143865-Large_12-430x323.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143865-Large_12.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143855-Large_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143863-Large_10.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143862-Large_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143864-Large_11.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143856-Large_3.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143857-Large_4.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143858-Large_5.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143859-Large_6.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143860-Large_7.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143861-Large_8.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143866-Large_13.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI-_143867-Large_14.webp",
    ],
    description: "Das Belinda Sofa Set kombiniert klassische Eleganz mit modernem Komfort. Ein zeitloser Klassiker, der jeden Raum veredelt.",
    fullDescription: "Das Belinda Sofa Set kombiniert klassische Eleganz mit modernem Komfort. Ein zeitloser Klassiker, der jeden Raum veredelt. Mit seinen eleganten Linien und hochwertigen Materialien vereint es die Besten aus beiden Welten. Das klassische Design wird durch moderne Komfortmerkmale ergänzt, was es zu einem vielseitigen Möbelstück macht, das über Generationen hinweg Bestand hat.",
    keyFeatures: [
      "Klassische Eleganz mit modernem Komfort",
      "Zeitloses Design für langfristige Wertschätzung",
      "Hochwertige Materialien und Verarbeitung",
      "Vielseitig für verschiedene Einrichtungsstile",
    ],
    additionalInfo: "Das Belinda Sofa Set ist ein zeitloser Klassiker, der in verschiedenen Konfigurationen erhältlich ist. Kontaktieren Sie uns für weitere Details.",
    href: "/kollektionen/belinda",
  },
  {
    id: "6",
    name: "Dream Sofa Set",
    slug: "dream",
    category: "Luxus-Gruppen",
    categorySlug: "luxury",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123984-Large_9-430x323.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123984-Large_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123977-Large_4.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123978-Large_5.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123979-Large_6.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123980-Large_7.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123983-Large_8.webp",
    ],
    description: "Das Dream Sofa Set macht Träume wahr mit seinem außergewöhnlichen Design und unvergleichlichem Komfort. Ein Meisterwerk der Möbelkunst.",
    fullDescription: "Das Dream Sofa Set macht Träume wahr mit seinem außergewöhnlichen Design und unvergleichlichem Komfort. Ein Meisterwerk der Möbelkunst. Mit seinen opulenten Formen, luxuriösen Materialien und perfekter Handwerkskunst schafft es eine Atmosphäre von unvergleichlichem Komfort und Eleganz. Jedes Detail wurde sorgfältig durchdacht, um ein Möbelstück zu schaffen, das sowohl funktional als auch ästhetisch außergewöhnlich ist.",
    keyFeatures: [
      "Außergewöhnliches Design und unvergleichlicher Komfort",
      "Opulente Formen mit luxuriösen Materialien",
      "Perfekte Handwerkskunst in jedem Detail",
      "Meisterwerk der Möbelkunst",
    ],
    additionalInfo: "Das Dream Sofa Set ist ein exklusives Stück, das in limitierter Auflage erhältlich ist. Für weitere Informationen kontaktieren Sie uns bitte.",
    href: "/kollektionen/dream",
  },
  {
    id: "7",
    name: "Efes Sofa Set",
    slug: "efes",
    category: "Moderne Gruppen",
    categorySlug: "modern",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123280-Large_10.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123280-Large_10.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123272-Large_3.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123271-Large_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123273-Large_4.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123274-Large_5.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123275-Large_6.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123281-Large_11.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123284-Large_13.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123285-Large_14.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123279-Large_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123287-Large_15.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_123288-Large_1.webp",
    ],
    description: "Das Efes Sofa Set überzeugt durch seine modernen Linien und einfaches, aber charaktervolles Design. Die speziell bemalten Holzleisten an den Armlehnen und die Holzfüße vereinen Natürlichkeit und Eleganz.",
    fullDescription: "Das Efes Sofa Set besticht durch seine modernen Linien und einfaches, aber charaktervolles Design. Die speziell bemalten Holzleisten an den Armlehnen und die Holzfüße vereinen Natürlichkeit und Eleganz. Seine minimalistische Form ist ideal für die Schaffung einer modernen und warmen Atmosphäre. Efes bietet komfortable Sitzgelegenheit mit seinem weich strukturierten Stoff und behält den Komfort auch bei längerer Nutzung bei. Sein leicht zu reinigender Stoff und stabiler Rahmen bieten sowohl eine ästhetische als auch funktionale Lösung.",
    keyFeatures: [
      "Speziell bemalte Holzfüße und dekorative Holzleisten an den Armlehnen",
      "Weich strukturierter, komfortabler und leicht zu reinigender Stoff",
      "Sitzstruktur mit modernen und einfachen Linien gestaltet",
      "Langlebige Rahmenstruktur und hochwertige Schaumstoffpolsterung",
    ],
    additionalInfo: "Das Efes Sofa Set ist in verschiedenen Farben und Stoffen erhältlich. Bitte kontaktieren Sie uns für weitere Informationen zu verfügbaren Optionen und Preisen.",
    href: "/kollektionen/efes",
  },
  {
    id: "8",
    name: "Lucas Sofa Set",
    slug: "lucas",
    category: "Moderne Gruppen",
    categorySlug: "modern",
    image: "https://cassalini.com/wp-content/uploads/2025/07/IMG_7683-Large_11_11zon.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7683-Large_11_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7665-Large_1_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7668-Large_2_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7686-Large_12_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7680-Large_9_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7670-Large_3_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7671-Large_4_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7674-Large_5_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7675-Large_6_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7677-Large_7_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7678-Large_8_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7682-Large_10_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/IMG_7689-Large_14_11zon.webp",
    ],
    description: "Das moderne Lucas Sofa Set vereint Funktionalität und Ästhetik in einem einzigartigen Design. Mit seinen modernen Linien komplettiert Lucas Ihre Wohnzimmereinrichtung und bietet gleichzeitig durch seine Funktion als Bett eine praktische Lösung für die Gästebetreuung.",
    fullDescription: "Das moderne Lucas Sofa Set vereint Funktionalität und Ästhetik in einem einzigartigen Design. Mit seinen modernen Linien komplettiert Lucas Ihre Wohnzimmereinrichtung und bietet gleichzeitig durch seine Funktion als Bett eine praktische Lösung für die Gästebetreuung. Das vielseitige Design macht es zu einem idealen Möbelstück für kleinere Wohnungen oder Gästezimmer, ohne dabei auf Komfort oder Stil verzichten zu müssen.",
    keyFeatures: [
      "Funktionalität als Sofa und Bett in einem",
      "Moderne Linien für zeitgenössische Wohnräume",
      "Praktische Lösung für Gästezimmer",
      "Kompaktes Design ohne Komfortverlust",
    ],
    additionalInfo: "Das Lucas Sofa Set ist ideal für kleinere Räume und bietet maximale Flexibilität. Kontaktieren Sie uns für weitere Informationen zu Größen und Optionen.",
    href: "/kollektionen/lucas",
  },
  {
    id: "9",
    name: "Luna Sofa Set",
    slug: "luna",
    category: "Moderne Gruppen",
    categorySlug: "modern",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133223-Large_8.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133223-Large_8.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133212-Large_1.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133227-Large_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133213-Large_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133221-Large_6.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133214-Large_3.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133215-Large_4.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133220-Large_5.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133222-Large_7.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133231-Large_11.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133233-Large_13.webp",
    ],
    description: "Das Luna Sofa Set bringt zeitgenössische Eleganz in Ihre Wohnräume mit seinem modernen Design und feinen Details. Mit seinem einfachen, aber auffälligen Erscheinungsbild bietet Luna sowohl Komfort als auch Ästhetik.",
    fullDescription: "Das Luna Sofa Set bringt zeitgenössische Eleganz in Ihre Wohnräume mit seinem modernen Design und feinen Details. Mit seinem einfachen, aber auffälligen Erscheinungsbild bietet Luna sowohl Komfort als auch Ästhetik. Die klaren Linien und die zurückhaltende Eleganz machen es zu einem vielseitigen Möbelstück, das sich nahtlos in verschiedene Einrichtungsstile einfügt. Mit hochwertigen Materialien und sorgfältiger Verarbeitung garantiert Luna langfristige Zufriedenheit.",
    keyFeatures: [
      "Zeitgenössische Eleganz mit modernem Design",
      "Einfaches, aber auffälliges Erscheinungsbild",
      "Hochwertige Materialien und sorgfältige Verarbeitung",
      "Vielseitig für verschiedene Einrichtungsstile",
    ],
    additionalInfo: "Das Luna Sofa Set ist in verschiedenen Konfigurationen erhältlich. Für weitere Informationen kontaktieren Sie uns bitte.",
    href: "/kollektionen/luna",
  },
  {
    id: "10",
    name: "Pablo Sofa Set",
    slug: "pablo",
    category: "Moderne Gruppen",
    categorySlug: "modern",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137400-Large_9.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137400-Large_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137387-Large_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137408-Large_10.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137395-Large_5.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137394-Large_4.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137397-Large_7.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137399-Large_8.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/Pablo_04-Large_11_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/Pablo_05-Large_12_11zon.webp",
    ],
    description: "Das Pablo Sofa Set besticht durch seine modernen Linien und vereint Eleganz und Komfort. Mit seiner weich strukturierten, speziellen Kumaş und eleganten Details bietet es sowohl eine ästhetisch ansprechende als auch funktionale Sitzgelegenheit.",
    fullDescription: "Das Pablo Sofa Set besticht durch seine modernen Linien und vereint Eleganz und Komfort. Mit seiner weich strukturierten, speziellen Kumaş und eleganten Details bietet es sowohl eine ästhetisch ansprechende als auch funktionale Sitzgelegenheit. Das moderne Design mit seinen klaren Linien und hochwertigen Materialien macht es zu einem idealen Möbelstück für zeitgenössische Wohnräume. Die besondere Stoffqualität sorgt für langfristigen Komfort und Langlebigkeit.",
    keyFeatures: [
      "Moderne Linien mit eleganter Ästhetik",
      "Weich strukturierter, spezieller Stoff",
      "Hochwertige Materialien für Langlebigkeit",
      "Funktionale und ästhetische Sitzgelegenheit",
    ],
    additionalInfo: "Das Pablo Sofa Set ist in verschiedenen Farben und Stoffen erhältlich. Kontaktieren Sie uns für weitere Informationen zu verfügbaren Optionen.",
    href: "/kollektionen/pablo",
  },
  {
    id: "11",
    name: "Pablo Ecksofa Set",
    slug: "pablo-corner",
    category: "Eckgruppen",
    categorySlug: "corner",
    image: "https://cassalini.com/wp-content/uploads/2025/07/casallini_143291-Large_7_11zon.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143291-Large_7_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143300-Large_1_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143297-Large_11_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143299-Large_13_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143306-Large_6_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143292-Large_8_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143293-Large_9_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143294-Large_10_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143298-Large_12_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143301-Large_2_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143302-Large_3_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143303-Large_4_11zon.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/casallini_143304-Large_5_11zon.webp",
    ],
    description: "Das Pablo Ecksofa ist ein einzigartiges Design, das moderne und sportliche Linien vereint. Es spricht einen urbanen und energiegeladenen Dekorationsstil an. Dank seiner klaren Linien verleiht es Ihrem Raum eine starke Präsenz.",
    fullDescription: "Das Pablo Ecksofa ist ein einzigartiges Design, das moderne und sportliche Linien vereint. Es spricht einen urbanen und energiegeladenen Dekorationsstil an. Dank seiner klaren Linien verleiht es Ihrem Raum eine starke Präsenz. Die L-Form ermöglicht optimale Raumnutzung und schafft eine gemütliche Ecke für entspannte Stunden. Mit seinem dynamischen Design und hochwertigen Materialien ist es perfekt für moderne, urbane Wohnräume.",
    keyFeatures: [
      "Einzigartiges Design mit modernen und sportlichen Linien",
      "L-Form für optimale Raumnutzung",
      "Urbanner und energiegeladener Dekorationsstil",
      "Starke Präsenz durch klare Linien",
    ],
    additionalInfo: "Das Pablo Ecksofa ist in verschiedenen Konfigurationen erhältlich. Kontaktieren Sie uns für weitere Informationen zu Größen und Optionen.",
    href: "/kollektionen/pablo-corner",
  },
  {
    id: "12",
    name: "Puma Sofa Set",
    slug: "puma",
    category: "Moderne Gruppen",
    categorySlug: "modern",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144091-Large_6.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144091-Large_6.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144083-Large_1.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144088-Large_4.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144084-Large_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144087-Large_3.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144089-Large_5.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144095-Large_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144096-Large_10.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144097-Large_11.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144098-Large_12.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144100-Large_13.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144101-Large_14.webp",
    ],
    description: "Das Puma Sofa Set wurde sorgfältig für diejenigen entwickelt, die ihren zeitgenössischen Wohnräumen Dynamik und Eleganz verleihen möchten. Dieses besondere Design, das für seine modernen Linien bekannt ist, passt sich mit seinem einfachen, aber auffälligen Erscheinungsbild jedem Dekorationsstil an.",
    fullDescription: "Das Puma Sofa Set wurde sorgfältig für diejenigen entwickelt, die ihren zeitgenössischen Wohnräumen Dynamik und Eleganz verleihen möchten. Dieses besondere Design, das für seine modernen Linien bekannt ist, passt sich mit seinem einfachen, aber auffälligen Erscheinungsbild jedem Dekorationsstil an. Mit hochwertigen Materialien und sorgfältiger Verarbeitung bietet Puma sowohl Komfort als auch Stil. Die dynamischen Formen und die elegante Ästhetik machen es zu einem Statement-Piece für moderne Wohnräume.",
    keyFeatures: [
      "Dynamisches Design mit modernen Linien",
      "Einfaches, aber auffälliges Erscheinungsbild",
      "Passt sich jedem Dekorationsstil an",
      "Hochwertige Materialien für Langlebigkeit",
    ],
    additionalInfo: "Das Puma Sofa Set ist in verschiedenen Konfigurationen erhältlich. Kontaktieren Sie uns für weitere Informationen zu verfügbaren Optionen und Preisen.",
    href: "/kollektionen/puma",
  },
  {
    id: "13",
    name: "Rixos Sofa Set",
    slug: "rixos",
    category: "Luxus-Gruppen",
    categorySlug: "luxury",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133955_1.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133955_1.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133951_11.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133953_12.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133945_6.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133954_13.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133946_7.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133947_8.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133948_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133949_10.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133956_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133959_4.webp",
    ],
    description: "Das Rixos Sofa Set bringt Eleganz und Komfort in jeden Raum Ihres Zuhauses. Der weiche, natürlich beige Stoff harmoniert perfekt mit der Holzstruktur.",
    fullDescription: "Das Rixos Sofa Set bringt Eleganz und Komfort in jeden Raum Ihres Zuhauses. Der weiche, natürlich beige Stoff harmoniert perfekt mit der Holzstruktur. Das Dreisitzer-Sofa und der Einzelsessel werden von hochdichtem Schaumstoff gestützt; sobald Sie sich setzen, entdecken Sie den Komfort. Die schlanken Metallfüße erheben sich vom Boden und verleihen dem Raum Leichtigkeit. Die praktisch zu reinigende Oberfläche macht den täglichen Gebrauch zum Vergnügen. Mit den eleganten Linien von Rixos wird Ihr Wohnzimmer in eine warme, einladende und moderne Atmosphäre gehüllt.",
    keyFeatures: [
      "Weicher, natürlich beiger Stoff in Harmonie mit Holzstruktur",
      "Hochdichter Schaumstoff für sofortigen Komfort",
      "Schlanke Metallfüße für moderne Leichtigkeit",
      "Praktisch zu reinigende Oberfläche",
    ],
    additionalInfo: "Das Rixos Sofa Set ist in verschiedenen Konfigurationen erhältlich. Kontaktieren Sie uns für weitere Informationen.",
    href: "/kollektionen/rixos",
  },
  {
    id: "14",
    name: "Rixos Ecksofa",
    slug: "rixos-corner",
    category: "Eckgruppen",
    categorySlug: "corner",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133964_1.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133964_1.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133968_5.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133972_8.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133965_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133966_3.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133967_4.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133971_7.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133975_10.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_133976_11.webp",
    ],
    description: "Das Rixos Ecksofa bietet mit seinem großzügigen und luftigen Sitzbereich Komfort und Eleganz für Ihr Zuhause. Der weiche, natürlich beige Stoff passt sich mühelos jeder Dekoration an.",
    fullDescription: "Das Rixos Ecksofa bietet mit seinem großzügigen und luftigen Sitzbereich Komfort und Eleganz für Ihr Zuhause. Der weiche, natürlich beige Stoff passt sich mühelos jeder Dekoration an. Dank der robusten Holzstruktur und des hochdichten Schaumstoffs bietet es langanhaltenden Komfort. Die schlanken Metallfüße schaffen ein modernes und elegantes Erscheinungsbild. Die praktisch zu reinigende Oberfläche erleichtert den täglichen Gebrauch. Das Rixos Ecksofa ist eine ideale Wahl sowohl für die Bewirtung Ihrer Gäste als auch zum Entspannen.",
    keyFeatures: [
      "Großzügiger und luftiger Sitzbereich",
      "Weicher, natürlich beiger Stoff für jede Dekoration",
      "Robuste Holzstruktur mit hochdichtem Schaumstoff",
      "Schlanke Metallfüße für modernes Design",
    ],
    additionalInfo: "Das Rixos Ecksofa ist in verschiedenen Konfigurationen erhältlich. Kontaktieren Sie uns für weitere Informationen.",
    href: "/kollektionen/rixos-corner",
  },
  {
    id: "15",
    name: "Tetra Sofa Set",
    slug: "tetra",
    category: "Moderne Gruppen",
    categorySlug: "modern",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI08-Large_1.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI08-Large_1.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI01-Large_8.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI02-Large_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI03-Large_10.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI04-Large_11.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI07-Large_14.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI05-Large_12.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI06-Large_13.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI09-Large_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI13-Large_6.webp",
    ],
    description: "Das Tetra Sofa Set wurde speziell für diejenigen entworfen, die minimalistische Dekoration bevorzugen, mit seiner schlichten Form und modernen Linien.",
    fullDescription: "Das Tetra Sofa Set wurde mit seiner schlichten Form und modernen Linien speziell für diejenigen entworfen, die minimalistische Dekoration bevorzugen. Dieses Set, das die schlichte Ästhetik ohne Rückenkissen in den Vordergrund stellt, verleiht Wohnzimmern mit seinen klaren und geraden Linien eine starke Haltung. Es ist eine perfekte Wahl für diejenigen, die einen Stil suchen, der mit wenigen Details viel aussagt. Die hohen und konisch gestalteten natürlichen Holzbeine bieten nicht nur Ästhetik, sondern auch Praktikabilität bei der Reinigung. Dank ihrer erhöhten Struktur vom Boden ist sie sowohl für Staubsaugerroboter geeignet als auch verleiht dem Sitzbereich ein Gefühl von Leichtigkeit.",
    keyFeatures: [
      "Schlichte Form ohne Rückenkissen für minimalistische Ästhetik",
      "Hohe konische natürliche Holzbeine",
      "Geeignet für Staubsaugerroboter",
      "Hochwertige Materialien und langlebige Struktur",
    ],
    additionalInfo: "Das Tetra Sofa Set ist ideal für minimalistische Wohnräume. Kontaktieren Sie uns für weitere Informationen zu Konfigurationen und Optionen.",
    href: "/kollektionen/tetra",
  },
  {
    id: "16",
    name: "Ürgüp Sofa Set",
    slug: "urgup",
    category: "Moderne Gruppen",
    categorySlug: "modern",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137418-Large_9.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137418-Large_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137413-Large_4.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137409-Large_1.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137410-Large_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137412-Large_3.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137414-Large_5.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137418-Large_9-1.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137415-Large_6.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137416-Large_7.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137417-Large_8.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137421-Large_11.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_137422-Large_12.webp",
    ],
    description: "Das Ürgüp Sofa Set verleiht Ihren Wohnräumen mit seinem Design, das Schlichtheit und moderne Ästhetik vereint, einen schlichten aber starken Charakter.",
    fullDescription: "Das Ürgüp Sofa Set verleiht Ihren Wohnräumen mit seinem Design, das Schlichtheit und moderne Ästhetik vereint, einen schlichten aber starken Charakter. Die quadratische Form der geraden Armlehnen und das kompakte Design, das mit der Rückenlehne integriert ist, hebt die moderne Linie des Sets hervor, während es sich mit seinem schlichten Stil leicht an jeden Dekorationsstil anpasst. Die in hoher Form gestalteten Holzbeine des Sets bieten sowohl ästhetisch als auch funktional große Vorteile. Dank der erhöhten Struktur vom Boden erleichtert sie die Reinigung und verleiht Ihrem Wohnzimmer ein luftigeres Aussehen.",
    keyFeatures: [
      "Quadratische gerade Armlehnen mit kompaktem Design",
      "Hohe Holzbeine für einfache Reinigung",
      "Langlebige Struktur mit hochwertigen Sitzkissen",
      "Nahtloses schlichtes Oberflächendesign",
    ],
    additionalInfo: "Das Ürgüp Sofa Set passt perfekt zu modernen, minimalistischen und natürlich strukturierten Räumen. Kontaktieren Sie uns für weitere Informationen.",
    href: "/kollektionen/urgup",
  },
  {
    id: "17",
    name: "Verona Sofa Set",
    slug: "verona",
    category: "Moderne Gruppen",
    categorySlug: "modern",
    image: "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144129-Large_12.webp",
    images: [
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144129-Large_12.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144121-Large_6.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144103-Large_2.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144118-Large_4.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144119-Large_5.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144122-Large_7.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144123-Large_8.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144124-Large_9.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144125-Large_10.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144130-Large_13.webp",
      "https://cassalini.com/wp-content/uploads/2025/07/CASALLINI_144136-Large_1.webp",
    ],
    description: "Das Verona Sofa Set fügt sich mit seinen einfachen Linien nahtlos in moderne Wohnräume ein. Sein bodennahes Design verleiht dem Set ein ausgewogenes und stabiles Erscheinungsbild.",
    fullDescription: "Das Verona Sofa Set fügt sich mit seinen einfachen Linien nahtlos in moderne Wohnräume ein. Sein bodennahes Design verleiht dem Set ein ausgewogenes und stabiles Erscheinungsbild. Die quadratischen Armlehnen sind mit klaren, geraden Linien gestaltet und verleihen dem Produkt einen modernen Charakter. Das Set vermeidet Prunk und bietet sowohl Schlichtheit als auch Eleganz. Der Stoff ist weich und leicht zu reinigen. Die Sitzkissen bieten Komfort. Sein langlebiger Rahmen gewährleistet eine langfristige Nutzung.",
    keyFeatures: [
      "Einfache Linien für moderne Wohnräume",
      "Bodennahes Design für Stabilität",
      "Quadratische Armlehnen mit klaren Linien",
      "Weicher und leicht zu reinigender Stoff",
    ],
    additionalInfo: "Das Verona Sofa Set ist eine gute Wahl für diejenigen, die einen minimalistischen Lebensstil bevorzugen. Kontaktieren Sie uns für weitere Informationen.",
    href: "/kollektionen/verona",
  },
];

// Helper functions
export function getAllProducts(): Product[] {
  return allProducts;
}

export function getProductBySlug(slug: string): Product | undefined {
  return allProducts.find((product) => product.slug === slug);
}

export function getProductsByCategory(categorySlug: "modern" | "luxury" | "corner" | "all"): Product[] {
  if (categorySlug === "all") {
    return allProducts;
  }
  const categoryName = categoryMap[categorySlug];
  return allProducts.filter((product) => product.category === categoryName);
}

export function getRelatedProducts(currentSlug: string, limit: number = 4): Product[] {
  const currentProduct = getProductBySlug(currentSlug);
  if (!currentProduct) return [];
  
  return allProducts
    .filter((product) => product.slug !== currentSlug && product.category === currentProduct.category)
    .slice(0, limit);
}
